#! /usr/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="docker/rmi/all -- process starting..."
printf "${CYAN}=== ${LABEL}${NO_COLOR}\n"


printf "${CYAN}=== docker - system prune${NO_COLOR}\n"
docker system prune --force
sleep 30;

printf "${CYAN}=== docker - remove all images${NO_COLOR}\n"
docker rmi --force $(docker images -aq)
sleep 30; 

docker images;