#! /usr/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="docker - system prune"
printf "${CYAN}=== ${LABEL}${NO_COLOR}\n"

docker system prune
sleep 30;

LABEL="docker - remove all images"
printf "${CYAN}========= ${LABEL}${NO_COLOR}\n"

docker rmi --force $(docker images -aq)
sleep 30; 

docker images;