#! /usr/bin/bash

# frontened
# s3 for client-side javascript bucket upload. 
source "$THEIA_WORKSPACE_ROOT/frontend-react-js/setup-s3"

# docker
docker compose -f "$THEIA_WORKSPACE_ROOT/docker-compose.yaml" up -d --build