#! /usr/bin/bash

docker compose down
IMAGE_ID=$(docker images -q aws-bootcamp-cruddur-2023-frontend-react-js)
docker rmi $IMAGE_ID
docker system prune -f 
docker compose -f "docker-compose.yaml" up -d --build