#! /usr/bin/bash

set -e # stop if it fails at any point.

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL='bootstrap'
printf "${CYAN} ========== ${LABEL} ========== ${NO_COLOR}\n"

ABS_PATH=$(readlink -f "$0")
BIN_DIR=$(dirname $ABS_PATH)

echo $BIN_DIR

source "$BIN_DIR/backend-flask/bin/rds/setup"
source "$BIN_DIR/backend-flask/bin/ddb/schema-load"
source "$BIN_DIR/backend-flask/bin/ddb/seed"

source "$BIN_DIR/aws/ecr/login"
source "$BIN_DIR/backend-flaks/generate-env"
source "$BIN_DIR/frontend-react-js/generate-env"