#! /usr/bin/bash

ABS_PATH=$(readlink -f "$0")
CDK_PATH=$(dirname $ABS_PATH)
BIN_PATH=$(dirname $CDK_PATH)
BACKEND_FLASK_PATH=$(dirname $BIN_PATH)
ROOT_PATH=$(dirname $BACKEND_FLASK_PATH)
SERVERLESS_CDK_PATH="$ROOT_PATH/serverless-cdk"

npm install 
rm -rf node_modules/sharp
SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp