      results = [
            # Reply template
            # {
            #   'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea--',
            #   'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109e--',
            #   'profile_picture': '/logo_mariachi_in_a_jar_white.png',
            #   'handle':  'Mariachi in a Jar',
            #   'message': 'placeholder',
            #   'commit_hash': '---',
            #   'commit_url': 'https://github.com/---',
            #   'image': '/image_path.png',
            #   'likes_count': 0,
            #   'replies_count': 0,
            #   'reposts_count': 0,
            #   'created_at': (now - timedelta(days=2)).isoformat()
            # },
        {  
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eha',
          'profile_picture': '/bubble_w05.png',
          'handle': 'Cruddur Campbot 05',
          'message': 'Week 05 - NoSQL & Caching',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'image': '/week05-livestream.png',
          'likes_count': 5,
          'replies_count': 2,
          'reposts_count': 0,
          'replies': [
            {
              'uuid': '26e12864-1c26-5c3a-9658-abc10f8fea71',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eha',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'place holder',
              'image': '',
              'commit_hash': '',
              'commit_url': '',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            },
            {
              'uuid': '26e12864-1c26-5c3a-9658-def10f8fea69',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eha',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'place holder',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }
          ],
        },
        {  
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eja',
          'profile_picture': '/bubble_w04.png',
          'handle': 'Cruddur Campbot 04',
          'message': 'Week 04 - Postgres and RDS',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'likes_count': 5,
          'replies_count': 2,
          'reposts_count': 0,
          'replies': [
            {
              'uuid': '26e12864-1c26-5c3a-9658-abc10f8fea71',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eha',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'place holder',
              'image': '',
              'commit_hash': '',
              'commit_url': '',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            },
            {
              'uuid': '26e12864-1c26-5c3a-9658-def10f8fea69',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eha',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'place holder',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }
          ],
        },
        {  
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeh',
          'profile_picture': '/bubble_w03.png',
          'handle': 'Cruddur Campbot 03',
          'message': 'Week 03 - Decentralized Authentication',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'likes_count': 5,
          'replies_count': 2,
          'reposts_count': 0,
          'replies': [
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea71',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeh',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 05 Saturday - Rewatched through the livestream👀, completed the follow-along.✍️',
              'commit_hash': '---',
              'commit_url': 'https://github.com/---',
              'image': '/week03-error-cognito03-accesstoken.png',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            },  
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea69',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeh',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': '[0200-0400, Feb 08 Sunday] Watched week 03 livestream and followed along the authentication process',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }
          ],
        },
        {  
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
          'profile_picture': '/bubble_w02.png',
          'handle': 'Cruddur Campbot 02',
          'message': 'Week 02 - Distributed Tracing with Honeycomb',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'likes_count': 4567,
          'replies_count': 6,
          'reposts_count': 0,
          'replies': [
              {
                'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea75',
                'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
                'profile_picture': '/logo_mariachi_in_a_jar_white.png',
                'handle':  'Mariachi in a Jar',
                'message': 'Week 04 Saturday - Implemented Rollbar successfully.',
                'commit_hash': '1bad7cc',
                'commit_url': 'https://github.com/CloudWest2023/aws-bootcamp-cruddur-2023/commit/1bad7cc1f691c5b92432417643f690ec1694ba8b',
                'image': '/week02-rollbar.png',
                'likes_count': 0,
                'replies_count': 0,
                'reposts_count': 0,
                'created_at': (now - timedelta(days=2)).isoformat()
              }, 
             {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea74',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 04 Thursday - Local Honeycomb configuration finally succeeded! T0T)...!',
              'commit_hash': '26008b1',
              'commit_url': 'https://github.com/CloudWest2023/aws-bootcamp-cruddur-2023/commit/26008b1468c473fe7dba6f7d3e3548f694525fa0',
              'image': '/week02-honeycomb-success.png',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea71',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 03 Tuesday - Migrating from Gitpod to Github Codespace. Open a workspace and reconfigured docker-compose file and devcontainer.json file following along Andrew\'s Codespace Crash Course.',
              'commit_hash': '28f3332',
              'commit_url': 'https://github.com/CloudWest2023/aws-bootcamp-cruddur-2023/commit/28f33323f7e117506aa6aebc62364218559e33bd',
              'image': '/week02-error-nospace.png',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea72',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 03 Monday - Week04 Sunday - Finished instrumenting Xray!',
              'image': '/week02-xray-daemon-working.png',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea73',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week04 Sunday - Implemented CloudWatch log, SUCCESS!',
              'image': '/week02-hw-cloudwatch-logs.png',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea69',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eeg',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 02 Sunday - Something went wrong with the Frontend. Doing this task all over again!',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea70',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eef',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 02 Monday morning 3 AM - sidetracked from notification feature because frontend is so much fun! lol. Updated homefeed page and Desktop Sidebar feature!',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }
          ],
        },
        {
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eef',
          'profile_picture': '/bubble_w01.png',
          'handle': 'Cruddur Campbot 01',
          'message': 'Week 01 - Create the notification feature (Backend and Front)',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'likes_count': 5,
          'replies_count': 2,
          'reposts_count': 0,
          'replies': [
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea65',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eef',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': '✅ *DynamoDB and Postgres vs Docker*: Created Music table, furnished it with my fav songs! [Week 02 Wednesday]',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea67',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eef',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': '✅ Write a Flask Backend Endpoint for Notifications - Something went wrong with the Frontend. Doing this task all over again! [Week 02 Sunday]',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea69',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eef',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': '🔍 Sidetracked from notification feature because frontend is so much fun! lol. Updated homefeed page and Desktop Sidebar feature! [Week 02 Monday morning 3 AM]',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }],
        },
        {
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eea',
          'profile_picture': '/bubble_w00.png',
          'handle': 'Cruddur Campbot 00',
          'message': 'Week 00 - Architecture and Billing',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'likes_count': 5,
          'replies_count': 2,
          'reposts_count': 0,
          'replies': 
          [
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea66',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eea',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 02 Sunday - Something went wrong with the Frontend. Doing this task all over again!',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }, 
            {
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea69',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eef',
              'profile_picture': '/logo_mariachi_in_a_jar_white.png',
              'handle':  'Mariachi in a Jar',
              'message': 'Week 02 Monday morning 3 AM - sidetracked from notification feature because frontend is so much fun! lol. Updated homefeed page and Desktop Sidebar feature!',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }
          ],
        },
        {
          'uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eee',
          'profile_picture': '/logo_matryoshka_in_the_cloud.png',
          'handle':  'Matryoshka in the Cloud',
          'message': 'Всем привет! Я хочу изучить Cloud.',
          'created_at': (now - timedelta(days=2)).isoformat(),
          'expires_at': (now + timedelta(days=5)).isoformat(),
          'likes_count': 5,
          'replies_count': 2,
          'reposts_count': 0,
          'replies': [{
            'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea67',
            'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eee',
            'profile_picture': '/logo_matryoshka_in_the_cloud.png',
            'handle':  'Matryoshka in the Cloud',
            'message': 'Я не поддерживаю войну.',
            'likes_count': 0,
            'replies_count': 0,
            'reposts_count': 0,
            'created_at': (now - timedelta(days=2)).isoformat(),
            'replies': [{
              'uuid': '26e12864-1c26-5c3a-9658-97a10f8fea66',
              'reply_to_activity_uuid': '68f126b0-1ceb-4a33-88be-d90fa7109eee',
              'handle':  'Matryoshka in the Cloud',
              'profile_picture': '/logo_matryoshka_in_the_cloud.png',
              'message': 'Слава Україні!',
              'likes_count': 0,
              'replies_count': 0,
              'reposts_count': 0,
              'created_at': (now - timedelta(days=2)).isoformat()
            }],
          }],
        },
        {
          'uuid': '66e12864-8c26-4c3a-9658-95a10f8fea67',
          'handle':  'Worf',
          'message': 'I am out of prune juice',
          'created_at': (now - timedelta(days=7)).isoformat(),
          'expires_at': (now + timedelta(days=9)).isoformat(),
          'likes': 0,
          'replies': []
        },
        {
          'uuid': '248959df-3079-4947-b847-9e0892d1bab4',
          'handle':  'Garek',
          'message': 'My dear doctor, I am just simple tailor',
          'created_at': (now - timedelta(hours=1)).isoformat(),
          'expires_at': (now + timedelta(hours=12)).isoformat(),
          'likes': 0,
          'replies': []
        }
      ]