#! /usr/bin/bash

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="docker/reset -- process starting..."
printf "${CYAN}== ${LABEL}${NO_COLOR}\n"

source $THEIA_WORKSPACE_ROOT/dock/down
sleep 20;
source $THEIA_WORKSPACE_ROOT/dock/rmi/all