#! /usr/bin/bash

ABS_PATH=$(readlink -f "$0")
BACKEND_FLASK_PATH=$(dirname $ABS_PATH)

# Leave out all the --build-args 
# as they will be injected when docker run.
docker build \
    -f "$BACKEND_FLASK_PATH/Dockerfile.prod" \
    -t backend-flask-prod \
    "$BACKEND_FLASK_PATH/."

# docker tag backend-flask-prod:latest $AWS_ECR_BACKEND_FLASK_URL_PROD:latest

# # Push image
# docker push $AWS_ECR_BACKEND_FLASK_URL_PROD:latest

    # --build-arg FRONTEND_URL="$FRONTEND_URL_PROD" \
    # --build-arg BACKEND_URL="$BACKEND_URL_PROD" \
    # --build-arg AWS_RDS_POSTGRES_ENDPOINT="$AWS_RDS_POSTGRES_ENDPOINT" \
    # --build-arg AWS_DYNAMODB_ENDPOINT="$AWS_DYNAMODB_ENDPOINT" \
    # --build-arg AWS_DYNAMODB_TABLE="$AWS_DYNAMODB_TABLE" \
    # --build-arg AWS_COGNITO_USER_POOL_ID="$AWS_COGNITO_USER_POOL_ID" \
    # --build-arg AWS_COGNITO_USER_POOL_CLIENT_ID="$AWS_COGNITO_USER_POOL_CLIENT_ID" \
    # --build-arg AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
    # --build-arg ROLLBAR_ACCESS_TOKEN="$ROLLBAR_ACCESS_TOKEN" \
    # -t backend-flask-prod \
    # -f Dockerfile.prod \