#! /usr/bin/bash

docker build \
    --build-arg AWS_COGNITO_USER_POOL_ID="$AWS_COGNITO_USER_POOL_ID" \
    --build-arg AWS_COGNITO_USER_POOL_CLIENT_ID="$AWS_COGNITO_USER_POOL_CLIENT_ID" \
    --build-arg AWS_DEFAULT_REGION="$AWS_DEFAULT_REGION" \
    --build-arg ROLLBAR_ACCESS_TOKEN="$ROLLBAR_ACCESS_TOKEN" \
    --build-arg FRONTEND_URL_PROD="$FRONTEND_URL_PROD" \
    --build-arg BACKEND_URL_PROD="$BACKEND_URL_PROD" \
    --build-arg URL_PROD="$URL_PROD" \
    --build-arg DB_NAME_PROD="$DB_NAME_PROD" \
    -t backend-flask-prod \
    -f Dockerfile.prod \
    .

docker tag backend-flask-prod:latest $AWS_ECR_BACKEND_REACT_PROD_URL:latest

# Push image
docker push $AWS_ECR_BACKEND_REACT_PROD_URL:latest