#! /usr/bin/bash

ABS_PATH=$(readlink -f "$0")
FRONTEND_REACT_JS_PATH=$(dirname $ABS_PATH)

# Leave out all the --build-args 
# as they will be injected when docker run.
docker build \
    -f "$FRONTEND_REACT_JS_PATH/Dockerfile.prod" \
    -t backend-flask-prod \
    "$FRONTEND_REACT_JS_PATH/."

#     --build-arg REACT_APP_BACKEND_URL="https://api.goodstuff.cloud" \
#     --build-arg REACT_APP_AWS_PROJECT_REGION="$AWS_DEFAULT_REGION" \
#     --build-arg REACT_APP_AWS_COGNITO_REGION="$AWS_DEFAULT_REGION" \
#     --build-arg REACT_APP_AWS_COGNITO_USER_POOL_ID="$AWS_COGNITO_USER_POOL_ID" \
#     --build-arg REACT_APP_AWS_COGNITO_USER_POOL_CLIENT_ID="$AWS_COGNITO_USER_POOL_CLIENT_ID" \
#     -t frontend-react-js-prod \
#     -f Dockerfile.prod \
#     .a