#! /usr/bin/bash

docker build \
    --build-arg REACT_APP_BACKEND_URL="https://api.cruddur.com" \
    --build-arg REACT_APP_AWS_PROJECT_REGION="$AWS_DEFAULT_REGION" \
    --build-arg REACT_APP_AWS_COGNITO_REGION="$AWS_DEFAULT_REGION" \
    --build-arg REACT_APP_AWS_COGNITO_USER_POOL_ID="$AWS_COGNITO_USER_POOL_ID" \
    --build-arg REACT_APP_AWS_COGNITO_USER_POOL_CLIENT_ID="$AWS_COGNITO_USER_POOL_CLIENT_ID" \
    -t frontend-react-js \
    -f Dockerfile.prod \
    .